#! /bin/bash


function usage() {
    echo "Usage: git wip [get|push]"
    return 0
}

function git_wip_push() {
    git fetch --prune
    local branch
    branch=wip-$(date +%s)

    git checkout -b "$branch"
    git add -A
    git commit -m "$branch"
    git push -u origin "$branch"

    local remote_wips
    remote_wips=$(git branch -r |grep -o "wip-.*" |grep -v "$branch")
    for remote_wip in $remote_wips; do
        git push origin :"$remote_wip"
    done
    return 0
}

function git_wip_get() {
    git fetch --prune
    local last_remote_wip
    last_remote_wip=$(git branch -r |grep -o "wip-.*" | tail -1 | sed -e 's#remotes/origin/##')
    git checkout "$last_remote_wip"
    return 0
}



if [ $# -lt 1 ]; then
    usage
    exit 1
fi


if [ "$1" == "get" ]; then
    git_wip_get
    exit 0
fi

if [ "$1" == "push" ]; then
    git_wip_push
    exit 0
fi

>&2 echo "git wip: Illegal option $1"
usage
exit 1


