#! /bin/bash

function usage() {
    echo "Usage:"
    echo "       git wip          checkout to a wip branch (if needed) and commit modified files"
    return 0
}

default_prefix="wip/"

function git_wip() {
    local current_branch
    current_branch=$(git branch --show-current)

    # If already in a "wip/..." branch, just commit and we are done.
    # If a corresponding "wip/..." branch already exists, fail and ask for
    # switching/cleaning
    if [[ ! $current_branch == wip\/* ]]; then
        if ! git branch "$default_prefix$current_branch"; then
            >&2 echo "ERROR: can not create branch $default_prefix$current_branch"
            exit 1
        fi
        if ! git switch "$default_prefix$current_branch"; then
            >&2 echo "ERROR: can not switch to branch $default_prefix$current_branch"
            exit 1
        fi
    fi
    for f in $(git add -A -n | awk '{print $2}'); do
        f="${f%\'}"
        f="${f#\'}"
        git add "$f" 
        git commit -m "[wip] $f"
    done
}

git_wip

